name: Build and Analyze with SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Analyze with SonarCloud
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'  # Defina a versão do PHP que você está utilizando no seu projeto
        extensions: mbstring, intl, bcmath, opcache, xml, sqlite3  # Extensões necessárias para o Hyperf (ajuste conforme seu projeto)
        coverage: none

    - name: Install dependencies
      run: |
        composer install --no-progress --prefer-dist

    - name: Run tests
      run: |
        composer run test  # Certifique-se de que você tenha um script "test" no seu composer.json que execute os testes (como PHPUnit)

    - name: Set up SonarCloud
      uses: sonarsource/sonarcloud-github-action@v2
      with:
        organization: "YOUR_ORG_NAME"   # Substitua pelo nome da sua organização no SonarCloud
        projectKey: "YOUR_PROJECT_KEY"  # Substitua pelo código de seu projeto no SonarCloud
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # O token gerado no SonarCloud (adicionado como secret no GitHub)

    - name: Run SonarCloud analysis
      run: |
        vendor/bin/sonar-scanner  # Executa a análise do SonarCloud
